kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    DishListView,
    IngredientListView,
    CookDetailView,
    DishDetailView,
    IngredientDetailView,
    DishCreateView,
    IngredientCreateView,
    CookCreateView,
    CookXPUpdateView,
    DishUpdateView,
    DishDeleteView,
    CookDeleteView,
    IngredientUpdateView,
    IngredientDeleteView, DishTypeCreateView
)

urlpatterns = [
    # <-----------Home------------------>
    path("", index, name="index"),
    # <-----------Cook Views-------------->
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/update/", CookXPUpdateView.as_view(), name="cook-xp-update"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    # <-----------Dish Views-------------->
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishtypes/create/", DishTypeCreateView.as_view(), name="type-create"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    # <-----------Ingredient Views-------------->
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/<int:pk>/", IngredientDetailView.as_view(), name="ingredient-detail"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(), name="ingredient-update"),
    path("ingredients/create/", IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),
]


app_name = "kitchen"

kitchen_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls")),
    path("accounts/", include("django.contrib.auth.urls")),

]

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link"><<</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">>></a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{% url 'kitchen:cook-detail' user.id%}">{{ user.get_username }}</a></li>
    <li class="list-group-item last"><a href="{% url 'logout'%}">Logout</a></li>
  {% else %}
    <li class="list-group-item last"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'kitchen:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'kitchen:cook-list' %}">Cooks</a></li>
  <li class="list-group-item"><a href="{% url 'kitchen:dish-list' %}">Menu</a></li>
  <li class="list-group-item"><a href="{% url 'kitchen:ingredient-list' %}">Ingredients</a></li>
</ul>