kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    DishListView,
    IngredientListView,
    CookDetailView,
    DishDetailView,
    IngredientDetailView,
    DishCreateView,
    IngredientCreateView,
    CookCreateView,
    CookXPUpdateView,
    DishUpdateView,
    DishDeleteView,
    CookDeleteView,
    IngredientUpdateView,
    IngredientDeleteView, DishTypeCreateView
)

urlpatterns = [
    # <-----------Home------------------>
    path("", index, name="index"),
    # <-----------Cook Views-------------->
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/update/", CookXPUpdateView.as_view(), name="cook-xp-update"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    # <-----------Dish Views-------------->
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishtypes/create/", DishTypeCreateView.as_view(), name="type-create"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    # <-----------Ingredient Views-------------->
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/<int:pk>/", IngredientDetailView.as_view(), name="ingredient-detail"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(), name="ingredient-update"),
    path("ingredients/create/", IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),
]


app_name = "kitchen"

kitchen_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls")),
    path("accounts/", include("django.contrib.auth.urls")),

]

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name} ({self.username})"


class Dish(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(unique=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    ingredients = models.ManyToManyField("Ingredient", related_name="dishes")
    dish_type = models.ManyToManyField(DishType, related_name="dishes")
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Dish, Ingredient, Cook, DishType


class DishTypeForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class CookForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class CookXPForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin


from kitchen.forms import IngredientForm, DishForm, CookForm, CookXPForm, IngredientSearchForm, DishSearchForm, \
    DishTypeForm
from kitchen.models import Cook, Dish, Ingredient, DishType


@login_required
def index(request: HttpRequest) -> HttpResponse:
    """View function for the home page of the site."""
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_visits": num_visits,
    }
    return render(request, "kitchen/index.html", context=context)


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__ingredients")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookXPUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookXPForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class DishListView(generic.ListView):
    model = Dish

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        context["dish_types"] = DishType.objects.all()
        return context

    def get_queryset(self) -> Dish:
        queryset = Dish.objects.all().prefetch_related("ingredients")
        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_form.html"
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    template_name = "kitchen/ingredient_list.html"
    context_object_name = "ingredient_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(IngredientListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = IngredientSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self) -> Ingredient:
        queryset = Ingredient.objects.all()
        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class IngredientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ingredient
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = "kitchen/ingredient_form.html"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("kitchen:ingredient-list")


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    template_name = "kitchen/dishtype_form.html"
    success_url = reverse_lazy("kitchen:dish-list")

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="main-content">
    <h1>Delete {{ cook.first_name }} {{ cook.last_name }}?</h1>
    <form action="" method="post">
      {% csrf_token %}
  
      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </section>
  
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
	<h1>
    Cook: {% if cook.first_name and cook.last_name %}{{ cook.get_full_name }}{% else %}{{ cook.username }}{% endif %}
    <a href="{% url 'kitchen:cook-delete' cook.id%}" class="btn btn-danger link-to-page update" style="float: right">
      Delete cook
    </a> 
  </h1>
  <section class="main-content">
    {% if cook.get_full_name %}
      <p><strong>First name:</strong> {{ cook.first_name }}</p>
      <p><strong>Last name:</strong> {{ cook.last_name }}</p>
    {% endif %}
    <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>
    <p>
      <strong>Experience:</strong> {{ cook.years_of_experience }} years
      <a href="{% url 'kitchen:cook-xp-update' cook.id %}" class="update">Update</a>
    </p>
  
    
    <h3>Dishes:</h3>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>
      {% for dish in cook.dishes.all %}
      <tr>
        <td><a href="{% url 'kitchen:dish-detail' dish.id%}">{{ dish.name }}</a></td>
        <td>{{ dish.description }}</td>
      </tr>
      {% endfor %}
    </table>
  </section>
  
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create cook</h1>
  <section class="main-content">
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
  
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </section>
  
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% block content %}
  <h1 class="header-content">
    <div class="header-content">Our cooks:</div>
    
    <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary link-to-page">
      Add cook
    </a>
  </h1>
  <section class="main-content">
    {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Full name</th>
        <th>Username</th>
        <th>Years of experience</th>
      </tr>
      {% for cook in cook_list %}
        <tr>
          <td>{{ cook.id }}</td>
          <td>{{ cook.get_full_name }}</td>
          <td><a href="{% url 'kitchen:cook-detail' cook.id%}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
          <td>{{ cook.years_of_experience }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No cooks are available.</p>
  {% endif %}
  </section>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="main-content">
    <h1>Delete {{ dish.name }}?</h1>
    <form action="" method="post">
      {% csrf_token %}
  
      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </section>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<h1>
    <div class="header-content">{{ dish.name }}</div>
    <a href="{% url 'kitchen:dish-update' dish.id%}" class="btn btn-success link-to-page update" style="float: right">
      Edit dish
    </a>  
    <a href="{% url 'kitchen:dish-delete' dish.id%}" class="btn btn-danger link-to-page update" style="float: right">
      Delete dish
    </a> 
  </h1>
  <section class="main-content">
{#    <img src="{% static 'images/'|add:dish.name.split.0|lower|add:'.jpeg' %}">#}
    <p><strong>Type:</strong> {% for type in dish.dish_type.all %}{{ type.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    <p><strong>Description:</strong> {{ dish.description }}</p>
    <p><strong>Ingredients:</strong> {% for ingredient in dish.ingredients.all %}{{ ingredient.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    <p><strong>Price:</strong> {{ dish.price }}</p>
    <p><strong>Cooks:</strong> {% for cook in dish.cooks.all %}<a href="{% url 'kitchen:cook-detail' cook.id %}">{{ cook.first_name }} {{ cook.last_name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  </section>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <section class="main-content">
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </section>

{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load query_transform %}

{% block content %}
  <h1>
  <div class="header-content">Our menu:</div>
    <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary link-to-page">
      Add dish
    </a>
    <a href="{% url 'kitchen:type-create' %}" class="btn btn-primary link-to-page">
      Add dish type
    </a>
  </h1>
  <section class="main-content">
    <form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input type="submit" value="🔍" class="btn btn-secondary">
    </form>
  {% if dish_list %}
    {% for dish_type in dish_types %}
      {% get_dishes_of_type dish_type.name as dishes %}
      {% if dishes %}
        <h1>{{ dish_type.name }}</h1>
        <table class="table menu" style="text-align: justify">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
          </tr>
          {% for dish in dishes %}
            <tr>
              <td><a href="{% url 'kitchen:dish-detail' dish.id%}">{{ dish.name }}</a></td>
              <td class="description-text">{{ dish.description }}</td>
              <td>{{ dish.price }}</td>
            </tr>
          {% endfor %}
        </table>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>No dishes in the menu yet.</p>
  {% endif %}
  </section>
{% endblock %}

templates/kitchen/dishtype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create dish type</h1>
  <section class="main-content">
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </section>

{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
  <h1 class="header-content">Welcome to the Grand Kitchen!</h1>
  <section class="main-content">
    <h3>On our website you can observe and manage the structure of the kitchen: add, update, or delete dishes and manage our cooks.</h3>
    <br>
  <div class="statistics">
    <div class="stat-item">
      <span class="stat-count">{{ num_cooks }}</span>
      <br>
      <span class="stat-label">Cooks</span>
    </div>
    <div class="stat-item">
      <span class="stat-count">{{ num_dishes }}</span>
      <br>
      <span class="stat-label">Dishes</span>
    </div>
  </div>

  <br>
  <p>You have visited home page <span class="visit-count">{{ num_visits }}</span> time{{ num_visits|pluralize }}</p>

  </section>
{% endblock %}

templates/kitchen/ingredient_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete ingredient?</h1>
  <section class="main-content">
    <p>This ingredient is in these dishes: 
    {% for dish in ingredient.dishes.all %}
      {{ dish.name }}
    {% endfor %}
  </p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </section>

{% endblock %}

templates/kitchen/ingredient_detail.html
{% extends "base.html" %}

{% block content %}
	<h1>
    <div class="header-content">{{ ingredient.name }}</div>
    <a href="{% url 'kitchen:ingredient-update' ingredient.id%}" class="btn btn-success link-to-page update" style="float: right">
      Edit ingredient
    </a>  
    <a href="{% url 'kitchen:ingredient-delete' ingredient.id%}" class="btn btn-danger link-to-page update" style="float: right">
      Delete ingredient
    </a> 
  </h1>
  <section class="main-content">
    <h3>Dishes that require {{ ingredient.name }}:</h3>
    {% for dish in ingredient.dishes.all %}
      <p>
      <strong>
        <a href="{% url 'kitchen:dish-detail' dish.id %}">
          {{ dish.name }}
        </a>
      </strong>
      </p>
    {% endfor %} 
  </section>
{% endblock %}

templates/kitchen/ingredient_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} ingredient</h1>
  <section class="main-content">
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </section>

{% endblock %}

templates/kitchen/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
	<h1>
    <div class="header-content">Our ingredients:</div>
    <a href="{% url 'kitchen:ingredient-create' %}" class="btn btn-primary link-to-page" style="float: right">
      Add ingredient
    </a>
  </h1>
  <section class="main-content">
    <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="🔍" class="btn btn-secondary">
    </form>
    {% if ingredient_list %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Number of dishes demanding</th>
        </tr>
        {% for ingredient in ingredient_list %}
          <tr>
            <td><a href="{% url 'kitchen:ingredient-detail' ingredient.id%}">{{ ingredient.name }}</a></td>
            <td>{{ ingredient.dishes.count }}</td>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  </section>

{% endblock %}